name = "co-roadmap"
compatibility_date = "2026-06-01"
type = "javascript"

# KV namespace binding
[[kv_namespaces]]
binding = "CO_ROADMAP_DATA"
id = "ca7f8dfc51ce4740aaaa04d29d50ebbf"
preview_id = "ca7f8dfc51ce4740aaaa04d29d50ebbf"

# Assets (static index.html)
[assets]
directory = "./public"
